"""Atlas: Betriebe, Erhebungen, Nachweise, Auswertungen

Revision ID: 41b6c7d2239f
Revises: 57adb37e9400
Erstellt: 2026-08-28 15:18:28.044564+02:00
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from belegwerk.kern.mandantentrennung import rls_aktivieren_sql
from sqlalchemy.dialects import postgresql

revision: str = '41b6c7d2239f'
down_revision: str | None = '57adb37e9400'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MANDANTENTABELLEN = [
    "atlas_auswertung",
    "atlas_betrieb",
    "atlas_erhebung",
    "atlas_nachweis",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atlas_betrieb',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strasse', sa.String(length=200), nullable=True),
    sa.Column('plz', sa.String(length=5), nullable=False),
    sa.Column('ort', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('art', sa.Enum('markengebunden', 'markengebunden_mehrmarken', 'frei', name='atlas_betriebsart'), nullable=False),
    sa.Column('marken', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('geprueft_am', sa.Date(), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_atlas_betrieb_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_betrieb'))
    )
    op.create_index(op.f('ix_atlas_betrieb_mandant_id'), 'atlas_betrieb', ['mandant_id'], unique=False)
    op.create_index('ix_atlas_betrieb_plz', 'atlas_betrieb', ['mandant_id', 'plz'], unique=False)
    op.create_table('atlas_auswertung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('plz_zentrum', sa.String(length=5), nullable=False),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ergebnis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdf_pfad', sa.String(length=500), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_atlas_auswertung_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_atlas_auswertung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_auswertung'))
    )
    op.create_index(op.f('ix_atlas_auswertung_mandant_id'), 'atlas_auswertung', ['mandant_id'], unique=False)
    op.create_table('atlas_erhebung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('betrieb_id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('erhebungsdatum', sa.Date(), nullable=False),
    sa.Column('art', sa.Enum('preisaushang', 'rechnung', 'schriftlich', 'telefonisch', 'fremdkalkulation', name='atlas_erhebungsart'), nullable=False),
    sa.Column('satz_mechanik', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('satz_karosserie', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('satz_elektrik', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('satz_lack_lohn', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('lack_material_prozent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lack_material_pauschale', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('upe_aufschlag_prozent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('verbringung_pauschale', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('entsorgung', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('im_pool', sa.Boolean(), nullable=False),
    sa.Column('erinnert_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_atlas_erhebung_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['betrieb_id'], ['atlas_betrieb.id'], name=op.f('fk_atlas_erhebung_betrieb_id_atlas_betrieb'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_atlas_erhebung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_erhebung'))
    )
    op.create_index(op.f('ix_atlas_erhebung_betrieb_id'), 'atlas_erhebung', ['betrieb_id'], unique=False)
    op.create_index('ix_atlas_erhebung_datum', 'atlas_erhebung', ['mandant_id', 'erhebungsdatum'], unique=False)
    op.create_index(op.f('ix_atlas_erhebung_mandant_id'), 'atlas_erhebung', ['mandant_id'], unique=False)
    op.create_table('atlas_nachweis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('erhebung_id', sa.UUID(), nullable=False),
    sa.Column('dateiname', sa.String(length=300), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('pfad', sa.String(length=500), nullable=False),
    sa.Column('bytes_gross', sa.Integer(), nullable=False),
    sa.Column('hochgeladen_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exif_entfernt', sa.Boolean(), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['erhebung_id'], ['atlas_erhebung.id'], name=op.f('fk_atlas_nachweis_erhebung_id_atlas_erhebung'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_atlas_nachweis_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atlas_nachweis'))
    )
    op.create_index(op.f('ix_atlas_nachweis_erhebung_id'), 'atlas_nachweis', ['erhebung_id'], unique=False)
    op.create_index(op.f('ix_atlas_nachweis_mandant_id'), 'atlas_nachweis', ['mandant_id'], unique=False)
    # ### end Alembic commands ###


    # Auch der Pool liest ausschliesslich ueber die Eigentuemerrolle; die
    # Anwendungsrolle bleibt strikt auf den eigenen Mandanten begrenzt.
    for anweisung in rls_aktivieren_sql(MANDANTENTABELLEN):
        op.execute(anweisung)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atlas_nachweis_mandant_id'), table_name='atlas_nachweis')
    op.drop_index(op.f('ix_atlas_nachweis_erhebung_id'), table_name='atlas_nachweis')
    op.drop_table('atlas_nachweis')
    op.drop_index(op.f('ix_atlas_erhebung_mandant_id'), table_name='atlas_erhebung')
    op.drop_index('ix_atlas_erhebung_datum', table_name='atlas_erhebung')
    op.drop_index(op.f('ix_atlas_erhebung_betrieb_id'), table_name='atlas_erhebung')
    op.drop_table('atlas_erhebung')
    op.drop_index(op.f('ix_atlas_auswertung_mandant_id'), table_name='atlas_auswertung')
    op.drop_table('atlas_auswertung')
    op.drop_index('ix_atlas_betrieb_plz', table_name='atlas_betrieb')
    op.drop_index(op.f('ix_atlas_betrieb_mandant_id'), table_name='atlas_betrieb')
    op.drop_table('atlas_betrieb')
    # ### end Alembic commands ###
