"""Check: Pruefungen, Befunde, eigene Regeln

Revision ID: e6ef04c0af16
Revises: b34f409052e0
Erstellt: 2026-08-28 14:43:31.678370+02:00
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from belegwerk.kern.mandantentrennung import rls_aktivieren_sql
from sqlalchemy.dialects import postgresql

revision: str = 'e6ef04c0af16'
down_revision: str | None = 'b34f409052e0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MANDANTENTABELLEN = ["check_befund", "check_feldmuster", "check_pruefung", "check_regel"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_feldmuster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feld', sa.String(length=80), nullable=False),
    sa.Column('muster', sa.String(length=300), nullable=False),
    sa.Column('prioritaet', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_check_feldmuster_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_feldmuster')),
    sa.UniqueConstraint('mandant_id', 'feld', 'muster', name='uq_check_feldmuster')
    )
    op.create_index(op.f('ix_check_feldmuster_mandant_id'), 'check_feldmuster', ['mandant_id'], unique=False)
    op.create_table('check_regel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kennung', sa.String(length=80), nullable=False),
    sa.Column('herkunft', sa.Enum('global', 'eigen', name='check_regelherkunft'), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('yaml_quelle', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_check_regel_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_regel')),
    sa.UniqueConstraint('mandant_id', 'kennung', name='uq_check_regel_kennung')
    )
    op.create_index(op.f('ix_check_regel_mandant_id'), 'check_regel', ['mandant_id'], unique=False)
    op.create_table('check_pruefung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('aktenzeichen', sa.String(length=120), nullable=True),
    sa.Column('dateiname', sa.String(length=300), nullable=False),
    sa.Column('dokument_hash', sa.String(length=64), nullable=False),
    sa.Column('upload_pfad', sa.String(length=500), nullable=True),
    sa.Column('seiten', sa.Integer(), nullable=False),
    sa.Column('gutachtenart', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('laeuft', 'fertig', 'fehlgeschlagen', name='check_pruefung_status'), nullable=False),
    sa.Column('fehlertext', sa.Text(), nullable=True),
    sa.Column('extraktion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('konfidenz', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('geprueft_regeln', sa.Integer(), nullable=False),
    sa.Column('nicht_entscheidbar', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fehlende_pflichtfelder', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_check_pruefung_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_check_pruefung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_pruefung'))
    )
    op.create_index('ix_check_pruefung_aktenzeichen', 'check_pruefung', ['mandant_id', 'aktenzeichen'], unique=False)
    op.create_index(op.f('ix_check_pruefung_mandant_id'), 'check_pruefung', ['mandant_id'], unique=False)
    op.create_table('check_befund',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pruefung_id', sa.UUID(), nullable=False),
    sa.Column('regel_id', sa.String(length=80), nullable=False),
    sa.Column('nummer', sa.Integer(), nullable=False),
    sa.Column('schwere', sa.Enum('fehler', 'warnung', 'hinweis', name='check_schwere'), nullable=False),
    sa.Column('titel', sa.String(length=300), nullable=False),
    sa.Column('meldung', sa.Text(), nullable=False),
    sa.Column('feldwerte', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seite', sa.Integer(), nullable=True),
    sa.Column('ausschnitt', sa.Text(), nullable=True),
    sa.Column('quittiert_von_id', sa.UUID(), nullable=True),
    sa.Column('quittiert_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quittierungsgrund', sa.Text(), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_check_befund_mandant_id_mandant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pruefung_id'], ['check_pruefung.id'], name=op.f('fk_check_befund_pruefung_id_check_pruefung'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quittiert_von_id'], ['benutzer.id'], name=op.f('fk_check_befund_quittiert_von_id_benutzer'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_befund'))
    )
    op.create_index(op.f('ix_check_befund_mandant_id'), 'check_befund', ['mandant_id'], unique=False)
    op.create_index(op.f('ix_check_befund_pruefung_id'), 'check_befund', ['pruefung_id'], unique=False)
    # ### end Alembic commands ###


    # Neue Tabellen brauchen ihre Policy, sonst sieht belegwerk_app sie nicht.
    for anweisung in rls_aktivieren_sql(MANDANTENTABELLEN):
        op.execute(anweisung)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_befund_pruefung_id'), table_name='check_befund')
    op.drop_index(op.f('ix_check_befund_mandant_id'), table_name='check_befund')
    op.drop_table('check_befund')
    op.drop_index(op.f('ix_check_pruefung_mandant_id'), table_name='check_pruefung')
    op.drop_index('ix_check_pruefung_aktenzeichen', table_name='check_pruefung')
    op.drop_table('check_pruefung')
    op.drop_index(op.f('ix_check_regel_mandant_id'), table_name='check_regel')
    op.drop_table('check_regel')
    op.drop_index(op.f('ix_check_feldmuster_mandant_id'), table_name='check_feldmuster')
    op.drop_table('check_feldmuster')
    # ### end Alembic commands ###
