"""Delta: Vorgaenge, Dokumente, Positionen, Abweichungen

Revision ID: 57adb37e9400
Revises: e6ef04c0af16
Erstellt: 2026-08-28 14:56:10.321965+02:00
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from belegwerk.kern.mandantentrennung import rls_aktivieren_sql
from sqlalchemy.dialects import postgresql

revision: str = '57adb37e9400'
down_revision: str | None = 'e6ef04c0af16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

MANDANTENTABELLEN = [
    "delta_abweichung",
    "delta_dokument",
    "delta_korrektur_log",
    "delta_position",
    "delta_vorgang",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delta_vorgang',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('aktenzeichen', sa.String(length=120), nullable=True),
    sa.Column('kennzeichen', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('angelegt', 'verarbeitung', 'korrektur_noetig', 'fertig', 'fehlgeschlagen', name='delta_vorgang_status'), nullable=False),
    sa.Column('fehlertext', sa.Text(), nullable=True),
    sa.Column('auftrag_id', sa.UUID(), nullable=True),
    sa.Column('ergebnis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auftrag_id'], ['auftrag.id'], name=op.f('fk_delta_vorgang_auftrag_id_auftrag'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_delta_vorgang_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_delta_vorgang_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delta_vorgang'))
    )
    op.create_index(op.f('ix_delta_vorgang_mandant_id'), 'delta_vorgang', ['mandant_id'], unique=False)
    op.create_index('ix_delta_vorgang_suche', 'delta_vorgang', ['mandant_id', 'aktenzeichen', 'kennzeichen'], unique=False)
    op.create_table('delta_dokument',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vorgang_id', sa.UUID(), nullable=False),
    sa.Column('rolle', sa.Enum('eigen', 'pruefbericht', name='delta_dokumentrolle'), nullable=False),
    sa.Column('dateiname', sa.String(length=300), nullable=False),
    sa.Column('dokument_hash', sa.String(length=64), nullable=False),
    sa.Column('quellformat', sa.String(length=10), nullable=False),
    sa.Column('adapter', sa.String(length=60), nullable=False),
    sa.Column('konfidenz', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('upload_pfad', sa.String(length=500), nullable=True),
    sa.Column('rohtext_pfad', sa.String(length=500), nullable=True),
    sa.Column('hinweise', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fahrzeug', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saetze', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summen', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_delta_dokument_mandant_id_mandant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vorgang_id'], ['delta_vorgang.id'], name=op.f('fk_delta_dokument_vorgang_id_delta_vorgang'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delta_dokument'))
    )
    op.create_index(op.f('ix_delta_dokument_mandant_id'), 'delta_dokument', ['mandant_id'], unique=False)
    op.create_index(op.f('ix_delta_dokument_vorgang_id'), 'delta_dokument', ['vorgang_id'], unique=False)
    op.create_table('delta_position',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dokument_id', sa.UUID(), nullable=False),
    sa.Column('laufnummer', sa.Integer(), nullable=False),
    sa.Column('art', sa.Enum('ERSATZTEIL', 'ARBEIT', 'LACK', 'NEBENKOSTEN', name='delta_positionsart'), nullable=False),
    sa.Column('bezeichnung', sa.String(length=400), nullable=False),
    sa.Column('teilenummer', sa.String(length=80), nullable=True),
    sa.Column('arbeitswerte', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stundensatz', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lackstufe', sa.Integer(), nullable=True),
    sa.Column('einzelpreis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aufschlag_prozent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rohzeile', sa.Text(), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dokument_id'], ['delta_dokument.id'], name=op.f('fk_delta_position_dokument_id_delta_dokument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_delta_position_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delta_position'))
    )
    op.create_index(op.f('ix_delta_position_dokument_id'), 'delta_position', ['dokument_id'], unique=False)
    op.create_index(op.f('ix_delta_position_mandant_id'), 'delta_position', ['mandant_id'], unique=False)
    op.create_table('delta_abweichung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vorgang_id', sa.UUID(), nullable=False),
    sa.Column('position_a_id', sa.UUID(), nullable=True),
    sa.Column('position_b_id', sa.UUID(), nullable=True),
    sa.Column('klasse', sa.Enum('POS_ENTFALLEN', 'POS_ERGAENZT', 'AW_REDUZIERT', 'LACKSTUFE_GESENKT', 'SATZ_GESENKT', 'UPE_GEKUERZT', 'VERBRINGUNG_ENTFALLEN', 'LACKMATERIAL_GEKUERZT', 'TEIL_ERSETZT', 'REP_STATT_TAUSCH', 'BETRAG_ABWEICHEND', name='delta_klasse'), nullable=False),
    sa.Column('art', sa.Enum('ERSATZTEIL', 'ARBEIT', 'LACK', 'NEBENKOSTEN', name='delta_positionsart'), nullable=False),
    sa.Column('laufnummer', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=400), nullable=False),
    sa.Column('differenz_netto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wert_eigen', sa.String(length=120), nullable=True),
    sa.Column('wert_pruefbericht', sa.String(length=120), nullable=True),
    sa.Column('beleg_eigen', sa.Text(), nullable=True),
    sa.Column('beleg_pruefbericht', sa.Text(), nullable=True),
    sa.Column('match_stufe', sa.Integer(), nullable=True),
    sa.Column('match_konfidenz', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('kommentar', sa.Text(), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_delta_abweichung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_a_id'], ['delta_position.id'], name=op.f('fk_delta_abweichung_position_a_id_delta_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_b_id'], ['delta_position.id'], name=op.f('fk_delta_abweichung_position_b_id_delta_position'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vorgang_id'], ['delta_vorgang.id'], name=op.f('fk_delta_abweichung_vorgang_id_delta_vorgang'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delta_abweichung'))
    )
    op.create_index(op.f('ix_delta_abweichung_mandant_id'), 'delta_abweichung', ['mandant_id'], unique=False)
    op.create_index(op.f('ix_delta_abweichung_vorgang_id'), 'delta_abweichung', ['vorgang_id'], unique=False)
    op.create_table('delta_korrektur_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dokument_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('feld', sa.String(length=80), nullable=False),
    sa.Column('wert_alt', sa.String(length=400), nullable=True),
    sa.Column('wert_neu', sa.String(length=400), nullable=True),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('zeit', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_delta_korrektur_log_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dokument_id'], ['delta_dokument.id'], name=op.f('fk_delta_korrektur_log_dokument_id_delta_dokument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_delta_korrektur_log_mandant_id_mandant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['delta_position.id'], name=op.f('fk_delta_korrektur_log_position_id_delta_position'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delta_korrektur_log'))
    )
    op.create_index(op.f('ix_delta_korrektur_log_dokument_id'), 'delta_korrektur_log', ['dokument_id'], unique=False)
    op.create_index(op.f('ix_delta_korrektur_log_mandant_id'), 'delta_korrektur_log', ['mandant_id'], unique=False)
    # ### end Alembic commands ###


    for anweisung in rls_aktivieren_sql(MANDANTENTABELLEN):
        op.execute(anweisung)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delta_korrektur_log_mandant_id'), table_name='delta_korrektur_log')
    op.drop_index(op.f('ix_delta_korrektur_log_dokument_id'), table_name='delta_korrektur_log')
    op.drop_table('delta_korrektur_log')
    op.drop_index(op.f('ix_delta_abweichung_vorgang_id'), table_name='delta_abweichung')
    op.drop_index(op.f('ix_delta_abweichung_mandant_id'), table_name='delta_abweichung')
    op.drop_table('delta_abweichung')
    op.drop_index(op.f('ix_delta_position_mandant_id'), table_name='delta_position')
    op.drop_index(op.f('ix_delta_position_dokument_id'), table_name='delta_position')
    op.drop_table('delta_position')
    op.drop_index(op.f('ix_delta_dokument_vorgang_id'), table_name='delta_dokument')
    op.drop_index(op.f('ix_delta_dokument_mandant_id'), table_name='delta_dokument')
    op.drop_table('delta_dokument')
    op.drop_index('ix_delta_vorgang_suche', table_name='delta_vorgang')
    op.drop_index(op.f('ix_delta_vorgang_mandant_id'), table_name='delta_vorgang')
    op.drop_table('delta_vorgang')
    # ### end Alembic commands ###
