"""Kerntabellen und Mandantentrennung

Revision ID: b34f409052e0
Revises: 
Erstellt: 2026-08-28 14:04:16.338874+02:00
"""

from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa

from belegwerk.kern.mandantentrennung import (
    app_rolle_anlegen_sql,
    mandant_tabelle_absichern_sql,
    rls_aktivieren_sql,
)
from sqlalchemy.dialects import postgresql

revision: str = 'b34f409052e0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Die mandantenbezogenen Tabellen dieser Revision. Bewusst ausgeschrieben:
# eine Migration muss unabhaengig vom heutigen Modellstand reproduzierbar sein.
MANDANTENTABELLEN = [
    "abonnement",
    "auftrag",
    "benutzer",
    "einladung",
    "passwort_marke",
    "rueckmeldung",
    "sitzung",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('briefkopf_zeilen', sa.Text(), nullable=True),
    sa.Column('logo_pfad', sa.String(length=500), nullable=True),
    sa.Column('aktenzeichen_muster', sa.String(length=200), nullable=True),
    sa.Column('llm_pfad_aktiv', sa.Boolean(), nullable=False),
    sa.Column('loeschung_beantragt_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandant'))
    )
    op.create_table('zugangsanfrage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('buero', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('modul', sa.String(length=20), nullable=True),
    sa.Column('bearbeitet', sa.Boolean(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zugangsanfrage'))
    )
    op.create_table('abonnement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modul', sa.Enum('delta', 'atlas', 'check', name='modul'), nullable=False),
    sa.Column('status', sa.Enum('testphase', 'aktiv', 'gekuendigt', 'abgelaufen', name='abonnement_status'), nullable=False),
    sa.Column('beginn', sa.Date(), nullable=False),
    sa.Column('ende', sa.Date(), nullable=True),
    sa.Column('preis_monat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_abonnement_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abonnement')),
    sa.UniqueConstraint('mandant_id', 'modul', name='uq_abonnement_mandant_modul')
    )
    op.create_index(op.f('ix_abonnement_mandant_id'), 'abonnement', ['mandant_id'], unique=False)
    op.create_table('auftrag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('art', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('wartet', 'laeuft', 'fertig', 'fehlgeschlagen', name='auftrag_status'), nullable=False),
    sa.Column('nutzlast', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fortschritt', sa.Integer(), nullable=False),
    sa.Column('schritt', sa.String(length=200), nullable=True),
    sa.Column('fehlertext', sa.Text(), nullable=True),
    sa.Column('versuche', sa.Integer(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gestartet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('beendet_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dauer_ms', sa.Integer(), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_auftrag_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auftrag'))
    )
    op.create_index(op.f('ix_auftrag_mandant_id'), 'auftrag', ['mandant_id'], unique=False)
    op.create_index('ix_auftrag_status_angelegt', 'auftrag', ['status', 'angelegt_am'], unique=False)
    op.create_table('benutzer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=False),
    sa.Column('rolle', sa.Enum('inhaber', 'mitarbeiter', name='rolle'), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('letzte_anmeldung', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_benutzer_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benutzer')),
    sa.UniqueConstraint('email', name='uq_benutzer_email')
    )
    op.create_index(op.f('ix_benutzer_mandant_id'), 'benutzer', ['mandant_id'], unique=False)
    op.create_table('einladung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('rolle', sa.Enum('inhaber', 'mitarbeiter', name='rolle'), nullable=False),
    sa.Column('laeuft_ab', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eingeloest_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt_von_id', sa.UUID(), nullable=True),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['erstellt_von_id'], ['benutzer.id'], name=op.f('fk_einladung_erstellt_von_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_einladung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_einladung')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_einladung_code_hash'))
    )
    op.create_index(op.f('ix_einladung_mandant_id'), 'einladung', ['mandant_id'], unique=False)
    op.create_table('passwort_marke',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=False),
    sa.Column('marke_hash', sa.String(length=64), nullable=False),
    sa.Column('laeuft_ab', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eingeloest_am', sa.DateTime(timezone=True), nullable=True),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_passwort_marke_benutzer_id_benutzer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_passwort_marke_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passwort_marke')),
    sa.UniqueConstraint('marke_hash', name=op.f('uq_passwort_marke_marke_hash'))
    )
    op.create_index(op.f('ix_passwort_marke_benutzer_id'), 'passwort_marke', ['benutzer_id'], unique=False)
    op.create_index(op.f('ix_passwort_marke_mandant_id'), 'passwort_marke', ['mandant_id'], unique=False)
    op.create_table('rueckmeldung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=True),
    sa.Column('seite', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('erledigt', sa.Boolean(), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_rueckmeldung_benutzer_id_benutzer'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_rueckmeldung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rueckmeldung'))
    )
    op.create_index(op.f('ix_rueckmeldung_mandant_id'), 'rueckmeldung', ['mandant_id'], unique=False)
    op.create_table('sitzung',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('benutzer_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('angelegt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('laeuft_ab', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zuletzt_gesehen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mandant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name=op.f('fk_sitzung_benutzer_id_benutzer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mandant_id'], ['mandant.id'], name=op.f('fk_sitzung_mandant_id_mandant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sitzung')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sitzung_token_hash'))
    )
    op.create_index(op.f('ix_sitzung_benutzer_id'), 'sitzung', ['benutzer_id'], unique=False)
    op.create_index(op.f('ix_sitzung_laeuft_ab'), 'sitzung', ['laeuft_ab'], unique=False)
    op.create_index(op.f('ix_sitzung_mandant_id'), 'sitzung', ['mandant_id'], unique=False)
    # ### end Alembic commands ###


    # --- Mandantentrennung in der Datenbank (Querschnitt 1.2) ---
    for anweisung in app_rolle_anlegen_sql():
        op.execute(anweisung)
    for anweisung in mandant_tabelle_absichern_sql():
        op.execute(anweisung)
    for anweisung in rls_aktivieren_sql(MANDANTENTABELLEN):
        op.execute(anweisung)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sitzung_mandant_id'), table_name='sitzung')
    op.drop_index(op.f('ix_sitzung_laeuft_ab'), table_name='sitzung')
    op.drop_index(op.f('ix_sitzung_benutzer_id'), table_name='sitzung')
    op.drop_table('sitzung')
    op.drop_index(op.f('ix_rueckmeldung_mandant_id'), table_name='rueckmeldung')
    op.drop_table('rueckmeldung')
    op.drop_index(op.f('ix_passwort_marke_mandant_id'), table_name='passwort_marke')
    op.drop_index(op.f('ix_passwort_marke_benutzer_id'), table_name='passwort_marke')
    op.drop_table('passwort_marke')
    op.drop_index(op.f('ix_einladung_mandant_id'), table_name='einladung')
    op.drop_table('einladung')
    op.drop_index(op.f('ix_benutzer_mandant_id'), table_name='benutzer')
    op.drop_table('benutzer')
    op.drop_index('ix_auftrag_status_angelegt', table_name='auftrag')
    op.drop_index(op.f('ix_auftrag_mandant_id'), table_name='auftrag')
    op.drop_table('auftrag')
    op.drop_index(op.f('ix_abonnement_mandant_id'), table_name='abonnement')
    op.drop_table('abonnement')
    op.drop_table('zugangsanfrage')
    op.drop_table('mandant')
    # ### end Alembic commands ###
